# Generated by Django 5.0 on 2023-12-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('message', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('zipcode', models.IntegerField()),
                ('suggestions', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
